INSERT INTO PUBLIC._RATINGS (name) VALUES ('G');
INSERT INTO PUBLIC._RATINGS (name) VALUES ('PG');
INSERT INTO PUBLIC._RATINGS (name) VALUES ('PG-13');
INSERT INTO PUBLIC._RATINGS (name) VALUES ('R');
INSERT INTO PUBLIC._RATINGS (name) VALUES ('NC-17');

INSERT INTO PUBLIC._GENRES (name) VALUES ('Комедия');
INSERT INTO PUBLIC._GENRES (name) VALUES ('Драма');
INSERT INTO PUBLIC._GENRES (name) VALUES ('Мультфильм');
INSERT INTO PUBLIC._GENRES (name) VALUES ('Триллер');
INSERT INTO PUBLIC._GENRES (name) VALUES ('Документальный');
INSERT INTO PUBLIC._GENRES (name) VALUES ('Боевик');