CREATE TABLE IF NOT EXISTS _films (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(150),
        description varchar(500),
        release_date date,
        duration INTEGER,
        rating_id INTEGER REFERENCES ratings (id)
);